import shutil
import sys
from pathlib import Path

import numpy as np


module_dir = Path(__file__).resolve().parent
code_dir = module_dir.parent

if str(code_dir) not in sys.path:
    sys.path.insert(
        0,
        str(code_dir),
    )


from explainability import config
from shared.modeling import (
    load_development_and_test,
    rebuild_final_model,
)


def main() -> None:
    # ---------------------------------------------------------
    # Configure Experiment 3 BEFORE importing shap_force.
    #
    # This is necessary because shap_force.py imports the
    # experiment-dependent paths from explainability.config.
    # ---------------------------------------------------------

    config.configure_experiment("3")

    from explainability.shap_force import (
        run_shap_force,
    )

    config.create_output_directories()

    # ---------------------------------------------------------
    # Load Experiment 3 development and held-out test data.
    # ---------------------------------------------------------

    (
        X_train,
        y_train,
        w_train,
        X_test,
        y_test,
        w_test,
    ) = load_development_and_test(
        config.TRAIN_DATA_PATH,
        config.TEST_DATA_PATH,
    )

    # ---------------------------------------------------------
    # Rebuild exactly the frozen final model already selected.
    # ---------------------------------------------------------

    (
        model,
        model_name,
        development_score,
        parameters,
    ) = rebuild_final_model(
        X_train=X_train,
        y_train=y_train,
        sample_weight=w_train,
        parameters_path=(
            config.FINAL_BEST_PARAMETERS_PATH
        ),
    )

    # ---------------------------------------------------------
    # Find the false negatives on the held-out test set.
    #
    # False negative:
    # true class      = phishing (-1)
    # predicted class = legitimate (1)
    # ---------------------------------------------------------

    y_pred = np.asarray(
        model.predict(X_test)
    )

    y_true = np.asarray(
        y_test
    )

    weights = np.asarray(
        w_test,
        dtype=float,
    )

    false_negative_positions = np.flatnonzero(
        (y_true == config.PHISHING_LABEL)
        & (y_pred != config.PHISHING_LABEL)
    )

    if false_negative_positions.size == 0:
        raise ValueError(
            "No false negatives were found "
            "in the Experiment 3 held-out test set."
        )

    # ---------------------------------------------------------
    # Choose one representative false negative.
    #
    # We use the FN with the largest retained-support weight,
    # so the choice is deterministic and not hand-picked.
    # ---------------------------------------------------------

    sample_position = int(
        false_negative_positions[
            np.argmax(
                weights[
                    false_negative_positions
                ]
            )
        ]
    )

    print("=" * 70)
    print(
        "FALSE NEGATIVE SHAP EXPLANATION "
        "- EXPERIMENT 3"
    )
    print("=" * 70)

    print(
        f"Model: {model_name}"
    )

    print(
        f"Development CV score: "
        f"{development_score:.4f}"
    )

    print(
        f"Number of false negatives: "
        f"{len(false_negative_positions)}"
    )

    print(
        "\nRepresentative false negative:"
    )

    print(
        f"Sample position: "
        f"{sample_position}"
    )

    print(
        f"Sample index: "
        f"{X_test.index[sample_position]}"
    )

    print(
        f"Sample weight: "
        f"{weights[sample_position]:.0f}"
    )

    print(
        f"True class: "
        f"{y_true[sample_position]}"
    )

    print(
        f"Predicted class: "
        f"{y_pred[sample_position]}"
    )

    # ---------------------------------------------------------
    # Generate the SAME SHAP force plot already used by
    # the project, but for the selected false negative.
    # ---------------------------------------------------------

    result = run_shap_force(
        model=model,
        X_background=X_train,
        X_test=X_test,
        sample_position=sample_position,
        class_to_explain=(
            config.CLASS_TO_EXPLAIN
        ),
    )

    # ---------------------------------------------------------
    # Keep the normal sample-specific output generated by
    # run_shap_force(), and additionally create a convenient
    # fixed-name copy for the report/slides.
    # ---------------------------------------------------------

    source_pdf = result["pdf_path"]

    if source_pdf is None:
        raise RuntimeError(
            "SHAP PDF generation is disabled. "
            "Set SAVE_PDF = True in explainability/config.py."
        )

    false_negative_pdf = (
        config.LOCAL_OUTPUT_DIR
        / "shap_force_false_negative.pdf"
    )

    shutil.copy2(
        source_pdf,
        false_negative_pdf,
    )

    print(
        "\nRepresentative false-negative "
        "SHAP force plot saved to:"
    )

    print(
        false_negative_pdf
    )

    print("=" * 70)


if __name__ == "__main__":
    main()
